version: '3'
services:
  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    ports:
      - ${ES_PORT}:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false